### PR TITLE
Mharradon/branches and loops

### PR DESCRIPTION
**Pull request by mharradon**
See #23

### CODE REVIEW

**Comment by dfdx** [comment]
Thanks for this smart PR! All in all, it looks good to me. I'm currently thinking about issues you raised in #23, but they won't block merging anyway.

**Comment by dfdx** [comment]
So regarding the issues raised in #23, I think we can postpone performance issues for now and just go with what we have at the moment. Overall, checking jumps between branches looks like a safety feature that can be turned on during development but turned off during execution. We can even set `should_assert_branches!(true)` by default for the tape, but remove it during compilation to speed up the execution. I don't have a clear vision for this yet, but keeping it configurable sound good enough for the start. 

Another reason I don't want to dive into these issues deeper is because the target state is not to check jumps, but support the complete control flow. Now with the release of Julia 1.7 it becomes a little bit closer, and I'm going to reconsider the approach to the tracer.
-----
Please also take a look at the inline comment [here](https://github.com/dfdx/Ghost.jl/pull/24/files#diff-9cfffbdde1240d3bbc48e12d9b70b84e4e53674af55fb22fabc01f465af7991cR235). Once it's done, I'm ready to merge!

**Comment by mharradon** [comment]
Yes, sorry, that's a bug on the main branch I added a test for and was trying to fix. There's an issue with constant valued conditions in `while` loops (possible in `if` conditionals as well). It causes an exception with loop tracing on or off.

I left it in as a reminder, but we can remove it from the PR if you like. I'll open a second issue.

**Comment by dfdx** [comment]
Got it, thanks!

**Pull request merged**
